export const SET_ENGLISH_TEXTS = "SET_ENGLISH_TEXTS";
export const SET_UNIQUE_KEYS = "SET_UNIQUE_KEYS";
export const SET_UNIQUE_KEYS_SORT_BY_USE_COUNT =
  "SET_UNIQUE_KEYS_SORT_BY_USE_COUNT";
export const SET_KEYS_TO_SHOW = "SET_KEYS_TO_SHOW";
export const SET_FOUND_TEXTS = "SET_FOUND_TEXTS";
